import type { SearchResponse } from '@/lib/api';
import { markdownToPlainText } from '@/lib/shareResearch';

export interface SessionCitation {
  index: number;
  source: string;
  title: string;
  url: string;
  doi: string | null;
  year: number;
  query: string;
  evidenceLevel?: string;
  note?: string;
  starred?: boolean;
}

export interface SessionEvidenceInput {
  personaLabel: string;
  dateLabel: string;
  userQueries: string[];
  summaries: Array<{
    query: string;
    summary: string;
    attached?: SearchResponse['attached_content'];
    pulseConfidence?: number;
    consensus?: string;
    keyFinding?: string;
    evidenceLevel?: string;
  }>;
  databases: string[];
  resultModes: string;
  totalResults: number;
  databaseCount: number;
  avgConfidence: number;
  bestEvidenceLabel: string;
  gaps: string[];
  citations: SessionCitation[];
  shareUrl?: string;
}

const SOURCE_LABELS: Record<string, string> = {
  pubmed: 'PubMed',
  clinical_trials: 'ClinicalTrials.gov',
  cochrane: 'Cochrane',
  who_iris: 'WHO IRIS',
  cdc: 'CDC',
  openalex: 'OpenAlex',
};

function sourceLabel(source: string): string {
  return SOURCE_LABELS[source]
    || source.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function stripFollowUps(text: string): string {
  return text.replace(/##\s*Suggested Follow[- ]?Ups?[\s\S]*$/i, '').trim();
}

/** ChatGPT-style friendly brief for clipboard and PDF export. */
export function buildSessionEvidenceDocument(input: SessionEvidenceInput): {
  title: string;
  markdown: string;
  plainText: string;
} {
  const shareUrl = input.shareUrl
    || (typeof window !== 'undefined' ? window.location.origin : 'https://lena-app.up.railway.app');

  const title = input.userQueries[0]
    ? `LENA Evidence Summary — ${input.userQueries[0].slice(0, 72)}${input.userQueries[0].length > 72 ? '…' : ''}`
    : 'LENA Evidence Summary';

  const md: string[] = [
    `# ${title}`,
    '',
    `**Prepared for:** ${input.personaLabel} · **Date:** ${input.dateLabel}`,
    `**Evidence level:** ${input.bestEvidenceLabel} · **PULSE:** ${input.avgConfidence}%`,
    '',
    '---',
    '',
    '## 🔬 Research question',
    '',
  ];

  input.userQueries.forEach((q, i) => {
    md.push(`${input.userQueries.length > 1 ? `${i + 1}. ` : ''}${q}`, '');
  });

  input.summaries.forEach((s, idx) => {
    if (!s.summary) return;
    const body = stripFollowUps(s.summary);
    md.push(
      idx === 0 ? '## 💡 What LENA found' : `## 💡 Findings (${idx + 1})`,
      '',
      body,
      '',
    );
    if (s.attached?.length) {
      md.push('### 📎 Attached sources reviewed', '');
      s.attached.forEach(a => {
        md.push(`- **${a.title || a.source}**${a.error ? ` _(could not read: ${a.error})_` : ''}`);
      });
      md.push('');
    }
  });

  md.push(
    '## 📊 Evidence snapshot',
    '',
    `- **${input.totalResults}** result${input.totalResults === 1 ? '' : 's'} across **${input.databaseCount}** database${input.databaseCount === 1 ? '' : 's'}`,
    `- Average PULSE confidence: **${input.avgConfidence}%**`,
    `- Databases searched: ${input.databases.map(sourceLabel).join(', ') || '—'}`,
    `- Result modes: ${input.resultModes}`,
    '',
  );

  input.summaries.forEach(s => {
    if (s.keyFinding) md.push(`- Key finding (*${s.query.slice(0, 60)}…*): ${s.keyFinding}`);
  });
  md.push('');

  if (input.gaps.length > 0) {
    md.push('## ⚠️ Gaps & limitations', '');
    input.gaps.forEach(g => md.push(`- ${g}`));
    md.push('');
  }

  if (input.citations.length > 0) {
    md.push('## 📚 References', '');
    input.citations.forEach(c => {
      const meta = `${sourceLabel(c.source)}${c.year ? ` (${c.year})` : ''}`;
      md.push(`${c.index}. ${c.starred ? '⭐ ' : ''}**${c.title}** — ${meta}`);
      if (c.doi) md.push(`   DOI: ${c.doi}`);
      if (c.url) md.push(`   ${c.url}`);
      if (c.note) md.push(`   _Note: ${c.note}_`);
      md.push('');
    });
  }

  md.push(
    '---',
    '',
    '⚠️ **Disclaimer:** Research evidence, not medical advice. Always consult a qualified healthcare provider for clinical decisions.',
    '',
    `🔬 Generated by **LENA** (Literature & Evidence Navigation Agent) · ${shareUrl}`,
  );

  const markdown = md.join('\n').trim();
  const plainText = markdownToPlainText(markdown)
    .replace(/🔬|💡|📊|📚|📎|⚠️|⭐/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return { title, markdown, plainText };
}
