import type { SessionEvidenceInput } from '@/lib/evidenceDocument';
import { buildSessionEvidenceDocument } from '@/lib/evidenceDocument';

const LENA_TEAL: [number, number, number] = [19, 107, 122];
const SLATE: [number, number, number] = [51, 65, 85];
const MUTED: [number, number, number] = [100, 116, 139];

function wrapText(doc: import('jspdf').jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

/** Export a friendly LENA evidence brief as PDF. */
export async function downloadEvidencePdf(input: SessionEvidenceInput, filename?: string): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const { title, plainText } = buildSessionEvidenceDocument(input);

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...LENA_TEAL);
  y = wrapText(doc, 'LENA Evidence Summary', margin, y, maxWidth, 22) + 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  y = wrapText(
    doc,
    `Prepared for ${input.personaLabel} · ${input.dateLabel} · PULSE ${input.avgConfidence}%`,
    margin,
    y,
    maxWidth,
    14,
  ) + 16;

  doc.setDrawColor(...LENA_TEAL);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  const blocks = plainText.split('\n\n').filter(Boolean);
  for (const block of blocks) {
    const isHeading = block.length < 80 && !block.includes('http') && /^[A-Z0-9]/.test(block);
    ensureSpace(isHeading ? 40 : 60);

    if (isHeading) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(...LENA_TEAL);
      y = wrapText(doc, block, margin, y, maxWidth, 16) + 10;
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...SLATE);
      y = wrapText(doc, block, margin, y, maxWidth, 14) + 12;
    }
  }

  ensureSpace(30);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  wrapText(
    doc,
    'Generated by LENA — Literature & Evidence Navigation Agent',
    margin,
    doc.internal.pageSize.getHeight() - margin,
    maxWidth,
    12,
  );

  const safeName = (filename || title).replace(/[^\w\s-]/g, '').trim().slice(0, 60);
  doc.save(`${safeName || 'LENA-Evidence-Brief'}.pdf`);
}
